// `aletheia init` — write inspection sidecars and a thin authority-diff
// workflow. Does not run or deploy the agent. Writes Aletheia inspection files.

import fs from "node:fs/promises";
import path from "node:path";
import { CONSENT_REL, gitToplevel } from "./cliCore";

export const POLICY_REL = ".aletheia/policy.json";
export const WORKFLOW_REL = ".github/workflows/capability-review.yml";

export const INIT_POLICY_JSON = `${JSON.stringify({ failOn: "elevated", rules: [] }, null, 2)}\n`;
export const INIT_CONSENT_JSON = `${JSON.stringify({ gated: {} }, null, 2)}\n`;

const ACTION_PLACEHOLDER = "PIN_COMMIT_SHA";

export function initWorkflowYaml(opts: {
  actionRef?: string;
  agentDirRel?: string;
}): string {
  const pin = opts.actionRef && /^[0-9a-f]{40}$/i.test(opts.actionRef)
    ? opts.actionRef.toLowerCase()
    : ACTION_PLACEHOLDER;
  const agentDir = opts.agentDirRel && opts.agentDirRel !== "" && opts.agentDirRel !== "."
    ? opts.agentDirRel.split(path.sep).join("/")
    : ".";
  const pinNote =
    pin === ACTION_PLACEHOLDER
      ? [
          "# Pin a full commit SHA of danielalbinsson/Aletheia before enabling this check.",
          `#   uses: danielalbinsson/Aletheia/.github/actions/capability-review@${ACTION_PLACEHOLDER}`,
        ]
      : [
          "# Generated by `aletheia init`. Inspection only — Aletheia does not run or",
          "# deploy the agent. The Action pin is an immutable commit SHA.",
        ];

  return [
    "name: Authority diff",
    "",
    ...pinNote,
    "",
    "on:",
    "  pull_request:",
    "    types: [opened, synchronize, reopened, labeled, unlabeled]",
    "",
    "permissions:",
    "  contents: read",
    "  pull-requests: write",
    "",
    "jobs:",
    "  review:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          fetch-depth: 0",
    "          persist-credentials: false",
    "      - uses: pnpm/action-setup@v4",
    "        with:",
    "          version: 9",
    "      - uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 24",
    "          cache: pnpm",
    "      - name: Install dependencies",
    "        run: pnpm install --frozen-lockfile",
    `      - uses: danielalbinsson/Aletheia/.github/actions/capability-review@${pin}`,
    "        with:",
    "          baseline: git:origin/${{ github.base_ref }}",
    "          fail-on: elevated",
    `          agent-dir: ${agentDir}`,
    "",
  ].join("\n");
}

/** @deprecated Use initWorkflowYaml() — kept for tests that read generated body. */
export const INIT_WORKFLOW_YAML = initWorkflowYaml({});

export interface InitWriteResult {
  written: string[];
  kept: string[];
}

export async function assertEveWorkspace(root: string): Promise<void> {
  const agentDir = path.join(root, "agent");
  try {
    const st = await fs.stat(agentDir);
    if (!st.isDirectory()) {
      throw new Error(`aletheia: not an eve agent workspace (agent/ is not a directory).`);
    }
  } catch (err) {
    if (err instanceof Error && err.message.startsWith("aletheia:")) throw err;
    throw new Error(`aletheia: not an eve agent workspace (missing agent/).`);
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}

function repoRelative(from: string, to: string): string {
  const rel = path.relative(from, to);
  if (rel === "") return ".";
  return rel.split(path.sep).join("/");
}

/** Write policy, consent, and the PR workflow if missing (or always with force). */
export async function writeInitFiles(
  root: string,
  opts: { force: boolean; actionRef?: string }
): Promise<InitWriteResult> {
  const agentRoot = path.resolve(root);
  const gitRoot = (await gitToplevel(agentRoot)) ?? agentRoot;
  const agentDirRel = repoRelative(gitRoot, agentRoot);
  const workflowBody = initWorkflowYaml({
    actionRef: opts.actionRef,
    agentDirRel,
  });

  const files: { destRoot: string; rel: string; body: string }[] = [
    { destRoot: agentRoot, rel: POLICY_REL, body: INIT_POLICY_JSON },
    { destRoot: agentRoot, rel: CONSENT_REL, body: INIT_CONSENT_JSON },
    { destRoot: gitRoot, rel: WORKFLOW_REL, body: workflowBody },
  ];
  const written: string[] = [];
  const kept: string[] = [];

  for (const { destRoot, rel, body } of files) {
    const dest = path.join(destRoot, rel);
    if (!opts.force && (await exists(dest))) {
      kept.push(rel);
      continue;
    }
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.writeFile(dest, body, "utf8");
    written.push(rel);
  }

  return { written, kept };
}
