// Render a passport from a PassportResult + facts.
//
// The generated markdown replaces the hand-authored PASSPORT.md files. That is
// the point: checklist item 7 ("a one-page passport") stops being a document
// someone writes to match the portrait and becomes an artifact derived from the
// same build the portrait comes from. If the two ever disagree, that is a bug,
// not a matter of authoring discipline.

import type { ManifestFacts } from "../parser/manifestAdapter";
import type { PassportResult, PassportCheck } from "../parser/passport";

export interface PassportMeta {
  headSha?: string;
  manifestSha?: string;
  generatedAt: string;
}

const STATUS_MARK: Record<PassportCheck["status"], string> = {
  pass: "PASS",
  fail: "FAIL",
  "advisory-pass": "PASS (advisory)",
  "advisory-fail": "SKIP (advisory)",
};

function bullets(items: string[]): string {
  return items.length ? items.map((i) => `- ${i}`).join("\n") : "- (none)";
}

/** Machine-readable result — this is what a gallery or CI reads to trust a badge. */
export function renderPassportJson(
  result: PassportResult,
  meta: PassportMeta
): string {
  return `${JSON.stringify(
    {
      schema: "aletheia.passport/v1",
      name: result.name,
      certified: result.certified,
      stamp: result.certified ? "Kit Certified" : "Not certified",
      failures: result.failures,
      generatedAt: meta.generatedAt,
      headSha: meta.headSha,
      manifestSha: meta.manifestSha,
      checks: result.checks.map((c) => ({
        id: c.id,
        title: c.title,
        required: c.required,
        status: c.status,
        detail: c.detail,
      })),
    },
    null,
    2
  )}\n`;
}

export function renderPassportMarkdown(
  result: PassportResult,
  facts: ManifestFacts,
  meta: PassportMeta
): string {
  const can = facts.capabilities.map((c) =>
    c.consent === "asks-first" ? `${c.label} (**asks first**)` : c.label
  );
  const reach = facts.reach.map((r) => r.label);
  const autonomy = facts.autonomy.map((a) => {
    const line = `${a.when}: ${a.does}`;
    return a.consent === "asks-first" ? `${line} (**asks first**)` : line;
  });
  const cannots = (facts.restrictions ?? []).map((r) => `${r.label} (\`${r.tool}\` disabled)`);
  const subagents = (facts.subagents ?? []).map((s) => s.name);

  const stampLine = result.certified
    ? "**Stamp:** Kit Certified — every required check passed (generated, not hand-authored)"
    : `**Stamp:** Not certified — ${result.failures} required check(s) failed (see below)`;

  const checklist = result.checks
    .map((c) => `| ${STATUS_MARK[c.status]} | ${c.title} | ${c.detail} |`)
    .join("\n");

  const provenance = meta.manifestSha
    ? `Generated from compiled manifest \`${meta.manifestSha.slice(0, 12)}\`${
        meta.headSha ? ` at commit \`${meta.headSha}\`` : ""
      }.`
    : "Generated from the compiled manifest.";

  return `# Capability passport — ${result.name}

${stampLine}
Generated by \`aletheia passport\` on ${meta.generatedAt}. Do not edit by hand — regenerate.

## Kit Certified checklist

| Result | Check | Detail |
| --- | --- | --- |
${checklist}

## What I can do

${bullets(can)}

## What I can touch

${bullets(reach)}

## What I do on my own

${bullets(autonomy)}
${subagents.length ? `\n## Subagents\n\n${bullets(subagents)}\n` : ""}
## What I cannot / will not do alone

${bullets(cannots)}

## How to verify

\`\`\`bash
eve build
npx @danielalbinsson/aletheia-cli passport --format json
\`\`\`

## Provenance

${provenance} Prefer **verified from build** facts. This is legibility tooling,
not a security audit. See https://agentic-kit.dev/docs/disclaimer
`;
}
